{% set version = "0.3.8" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-profvis
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/profvis_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/profvis/profvis_{{ version }}.tar.gz
  sha256: ec02c75bc9907a73564e691adfa8e06651ca0bd73b7915412960231cd265b4b2

build:
  merge_build_host: true  # [win]
  skip: true              # [ppc64le]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-htmlwidgets >=0.3.2      # [build_platform != target_platform]
    - r-purrr                    # [build_platform != target_platform]
    - r-rlang >=0.4.9            # [build_platform != target_platform]
    - r-stringr                  # [build_platform != target_platform]
    - r-vctrs                    # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - r-base
    - r-htmlwidgets >=0.3.2
    - r-purrr
    - r-rlang >=0.4.9
    - r-stringr
    - r-vctrs
  run:
    - r-base
    - {{ native }}gcc-libs       # [win]
    - r-htmlwidgets >=0.3.2
    - r-purrr
    - r-rlang >=0.4.9
    - r-stringr
    - r-vctrs

test:
  commands:
    - $R -e "library('profvis')"           # [not win]
    - "\"%R%\" -e \"library('profvis')\""  # [win]

about:
  home: https://rstudio.github.io/profvis/
  dev_url: https://github.com/rstudio/profvis
  license: GPL-3.0-only
  summary: Interactive visualizations for profiling R code.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - halldc
